# Generated by Django 3.2.6 on 2021-08-16 12:43

from django.db import migrations, models
import django.db.models.deletion
import gr.models


class Migration(migrations.Migration):

    dependencies = [
        ('gr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не установлено', max_length=255, verbose_name='Название параметра сортировки')),
            ],
            options={
                'verbose_name': 'Поле сортировки',
                'verbose_name_plural': 'Поля сортировок',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gr',
            name='sort',
            field=models.ForeignKey(default=gr.models.get_default_sort, on_delete=django.db.models.deletion.SET_DEFAULT, to='gr.grsort', verbose_name='Описалово подсказки'),
        ),
    ]
