# Generated by Django 3.2.6 on 2021-08-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gr', '0002_auto_20210816_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(upload_to='./', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='gr',
            name='object_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gr.grtype', verbose_name='grType'),
        ),
    ]
