# Generated by Django 3.2.6 on 2021-08-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gr', '0003_auto_20210816_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='gr',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gr.grfile', verbose_name='Файл обьекта'),
        ),
    ]
