# Generated by Django 3.2.6 on 2021-08-16 13:29

from django.db import migrations, models
import mainxz.utils


class Migration(migrations.Migration):

    dependencies = [
        ('gr', '0004_gr_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gr',
            name='file',
        ),
        migrations.AddField(
            model_name='gr',
            name='file',
            field=models.ManyToManyField(blank=True, null=True, to='gr.GrFile', verbose_name='Файл обьекта'),
        ),
        migrations.AlterField(
            model_name='grfile',
            name='src',
            field=models.FileField(upload_to=mainxz.utils.create_file_upload_path, verbose_name='Файл'),
        ),
    ]
