# Generated by Django 3.2.6 on 2021-08-16 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gr1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.BooleanField(default=False, verbose_name='Подтверждено (готово к использованию)')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название объекта')),
                ('texts', models.JSONField(null=True, verbose_name='Языки (обьект с переводами)')),
                ('json', models.JSONField(blank=True, null=True, verbose_name='JSON объекта')),
                ('icon', models.CharField(default='resources/image/notpic1.png', max_length=512, verbose_name='Иконка')),
                ('iconId', models.PositiveIntegerField(default=0, verbose_name='Айди иконки (нет защиты отношения в базе данных (можно задать любой))')),
                ('object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gr1.grtype', verbose_name='TYPE_VERBOSEzdsdsgf')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь объекта')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'abstract': False,
            },
        ),
    ]
