# Generated by Django 3.1.4 on 2021-08-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group2',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
