# Generated by Django 3.1.4 on 2021-08-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group1', '0002_auto_20210818_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group1',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
